name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: |
            "website/package-lock.json"
            "slides/package-lock.json"

      - name: Install dependencies (slides)
        working-directory: slides
        run: |
          npx -y playwright@^1.41.2 install chromium
          npm ci
      
      - name: Build slides for ACS CC
        working-directory: slides
        run: SLIDES_OUTPUT_FOLDER=../website/static/slides ./build.sh acs_cc 
  
      - name: Build slides for FILS English
        working-directory: slides
        run: SLIDES_OUTPUT_FOLDER=../website/static/slides ./build.sh fils_en 

      - name: Install dependencies (website)
        working-directory: website
        run: npm ci
      
      - name: Build website
        working-directory: website
        run: npm run build

      # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./website/build
          cname: embedded-rust-101.wyliodrin.com
          # The following lines assign commit authorship to the official
          # GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # You can swap them out with your own user credentials.
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
