name: Test deployment

on:
  pull_request:
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on
  merge_group:

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: |
            website/package-lock.json
            slides/package-lock.json
      
      - name: Install dependencies (slides)
        working-directory: slides
        run: |
          npx -y playwright@^1.41.2 install chromium
          npm ci

      - name: Build slides for ACS CC
        working-directory: slides
        run: SLIDES_OUTPUT_FOLDER=../website/static/slides ./build.sh acs_cc 

      - name: Build slides for FILS English
        working-directory: slides
        run: SLIDES_OUTPUT_FOLDER=../website/static/slides ./build.sh fils_en 

      - name: Install dependencies (website)
        working-directory: website
        run: npm ci

      - name: Test build website
        working-directory: website
        run: npm run build
